server:
  port: 1000

spring:
  application:
    name: mrk-gateway
  cloud:
    # 注册中心配置
    nacos:
      discovery:
        server-addr: 124.222.46.195:8848
      config:
        server-addr: 124.222.46.195:8848
    gateway:
      # 全局的跨域配置
      globalcors:
        # 解决options请求被拦截问题
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          # 拦截的请求
          '[/**]':
            # 允许跨域的请求
            allowedOrigins: "*" # spring boot2.4以前的配置
            #allowedOriginPatterns: "*" # spring boot2.4以后的配置
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 是否允许携带cookie
            alloweCredentials: true
            # 跨域检测的有效期,单位s
            maxAge: 36000
      discovery:
    # 允许通过服务名称进行路由转发访问， http://service-id/user
        locator:
          enabled: true
  # 路由配置
      routes:
#        - id: stock-user
#          uri: lb://stock-user
#          predicates:
#            - Path=/user/**
        - id: mrk-auth
          uri: lb://mrk-auth
          predicates:
            # - Method=GET,POST  不要开启此项
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: mrk-user
          uri: lb://mrk-system
          predicates:
            # - Method=GET,POST  不要开启此项
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: mrk-chat
          uri: lb://mrk-chat
          predicates:
            # - Method=GET,POST  不要开启此项
            - Path=/chat/**
          filters:
            - StripPrefix=1

  # redis
  redis:
    ##redis 单机环境配置
    host: 124.222.46.195
    port: 6379
    password: apollotest
    database: 0
    ssl: false
# magicRepoKit服务配置
mrk:
  token:
    sing-key: mrkmrkisapowerfulmicroservicearchitectureupgradedandoptimizedfromacommercialproject


knife4j:
  gateway:
    # 是否开启
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      # 是否开启
      enabled: true
      version: swagger2
      excluded-services:
        - mrk-gateway
        - mrk-auth
      swagger2:
        url: /v2/api-docs?group=default
